#database 연동
spring:
  profiles:
    group:
      local:
        - dev
        - oauth2
        - aws
    active: local
  thymeleaf:
    cache: false
#jpa database 설정
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
